### ISSUE TITLE
Plugin doesn't start

### ISSUE THREAD

**Issue by pixelpeter67** [wirbel-at-vdr-portal/vdr-plugin-satip#3]
ERROR: /vdr/plugins/libvdr-satip.so.2.6.3: undefined symbol: _Z9UpperCaseNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
ldd there is no reference to the plugin to librepfunc.
librepfunc ist installed correctly
system ist debian buster

**Comment by wirbel-at-vdr-portal** [comment]
For newer debians, librepfunc-dev might be available via installer. From source is perfect as well.

Looks like Makefile variable $(LIB) lacks a ' -lrepfunc', see vdr-portal thread.

**Comment by pixelpeter67** [comment]
problem solved

**Comment by wirbel-at-vdr-portal** [comment]
solved -> closed
