### ISSUE TITLE
repfunc.h

### ISSUE THREAD

**Issue by jsffm** [wirbel-at-vdr-portal/vdr-plugin-satip#7]
Compile Error

param.c:11:10: fatal error: repfunc.h: No such file or directory
   11 | #include <repfunc.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:96: param.o] Error 1
make: *** Waiting for unfinished jobs....
tuner.c:21:10: fatal error: repfunc.h: No such file or directory
   21 | #include <repfunc.h>
      |          ^~~~~~~~~~~
compilation terminated.

**Comment by wirbel-at-vdr-portal** [comment]
From the README:

  Requirements.
  In addition to the original requirements below, the following sources
  are needed to build this version of the plugin:
      - librepfunc >= 1.7.0**
       https://github.com/wirbel-at-vdr-portal/librepfunc

**Comment by jsffm** [comment]
Should be added to the normal requirements
