### ISSUE TITLE
vdr new powersvemode (not ready or Bug)

### ISSUE THREAD

**Issue by geraldraaf** [wirbel-at-vdr-portal/vdr-plugin-satip#8]
Hi,
with vdr 2.6.7 the tuner in minisatip are released (going in status offline) when i detach softhddevice, as Klaus wrote (in 2.6.8 anouncement) the powersafemode and maybe lnbPowerTurnedOn has to be implemented in the plugins.

My Question is it implemented or is it a bug in satip-plugin, or softhddevice or maybe in vdr.

i did the tests with following Sonftware 

- vdr 2.6.7, 2.6.8 and 2.6.9 no patches
- and actual git-version vdr-plugin-satip
- softhddevice (https://github.com/ua0lnj/vdr-plugin-softhddevice).
- and as Sat>IP Server minisatip v1.3.16

kind regards

**Comment by wirbel-at-vdr-portal** [comment]
I don't understand your issue yet.
If a tuner is detached, that sounds like it should, if vdr request the satip device to do so?

Regarding implementation, it's implemented in this fork of the satip plugin, but not yet well tested.

May be better to open a thread at vdr-portal.de

**Comment by geraldraaf** [comment]
I did some more tests it is with all vdr versions, i will close this issue and open an new in softhddevice

1. When i start vdr with softhddevice in detached mode (screenshot_1.png), it looks like the next picture.
![screenshot_1](https://github.com/user-attachments/assets/cc02369c-e128-478d-9e2c-6be98a1e17df)


2. when i start vdr only with satip plugin it looks like the next picture and after a while it looks like in 3.
![screenshot_0](https://github.com/user-attachments/assets/50151fdc-52ce-4665-afa6-321e2b7d54a4)


3. status after some time with 2. or when i attach and detach softhddevice, so i think it's a problem with softhddevice.
![screenshot_2](https://github.com/user-attachments/assets/251164d3-e6de-4016-95a4-d137877300ee)

**Comment by wirbel-at-vdr-portal** [comment]
So, the satip plugin is able to close sessions with the satip server after inactivity of EPG scan.

With VDR-2.6.9, it's expected only such devices to close, which have been opened and used for EPG scan and are now no longer in use for EPG scan. I would expect to have at least one device blocked for live tv, no matter if your output device is shutdown or not. And once every xxx hours as much as avail devices for EPG scan, which might be closed afterwards.
